FROM python:3.9
LABEL maintainer="Emerson Faria"
LABEL version="1.0"

# Instala aplicações básicas para caso precise vasculhar um contêiner da imagem
RUN apt-get update
RUN apt-get install nano

# Cria um diretório Base na imagem
RUN mkdir -p /interface

# Copia todo o conteúdo para o diretório Base
COPY . /interface

# Determina qual o diretório "padrão" do contêiner quando o mesmo iniciar
WORKDIR /interface

# Instala pacotes Python
RUN pip install --upgrade pip
RUN pip install -r /interface/requirements.txt

# Expõe para o HOST algumas portas, por padrão
EXPOSE 80
EXPOSE 7860